// -*- C++ -*-
//
//*****************************************************************
//
// WARRANTY:
// Use all material in this file at your own risk.
//
// This file is auto-generated by python script on 2018-01-28 05:15:31.437789
//
//*****************************************************************

#ifndef EXCHANGE_ENUMS_H
#define EXCHANGE_ENUMS_H

#include <algorithm>
#include <cassert>
#include <iostream>

enum class exchange_t {
  NOEXCHANGE = -3,
  COINAPI = -2,
  COINMARKETCAP = -1,
  OKCOIN_CNY = 0,
  POLONIEX,
  BITTREX,
  BITFINEX,
  BTCCHINA,
  KRAKEN,
  COINBASE,
  BITSTAMP,
  OKCOIN_USD,
  BTCTRADE,
  GEMINI,
  ITBIT,
  HUOBI,
  BTC_E,
  COINCHECK,
  BITHUMB,
  HITBTC,
  COINONE,
  CHBTC,
  BINANCE,
  EXMO,
  CRYPTOPIA,
  LIQUI,
  JUBI,
  BTC38,
  KORBIT,
  MTGOX,
  LAKEBTC,
  BLEUTRADE,
  YOBIT,
  BITFLYER,
  BTER,
  ACX,
  VIRWOX,
  OKEX,
  THEROCKTRADING,
  MERCADOBITCOIN,
  QUOINE,
  BITMARKET,
  BITSO,
  VAULTORO,
  CCEX,
  GATECOIN,
  QUADRIGACX,
  COINMATE,
  BXINTH,
  COINFLOOR,
  INDEPENDENTRESERVE,
  COINNEST,
  WEXNZ,
  DERIBIT,
  BTCX,
  DSX,
  YUNBI,
  BITKONAN,
  BTCC,
  BITBAY,
  BTCTURK,
  XBTCE
};

static std::vector<std::string> g_exchange_strs = {"NOEXCHANGE",     "COINAPI",    "COINMARKETCAP",
                                                   "OKCOIN_CNY",     "POLONIEX",   "BITTREX",
                                                   "BITFINEX",       "BTCCHINA",   "KRAKEN",
                                                   "COINBASE",       "BITSTAMP",   "OKCOIN_USD",
                                                   "BTCTRADE",       "GEMINI",     "ITBIT",
                                                   "HUOBI",          "BTC-E",      "COINCHECK",
                                                   "BITHUMB",        "HITBTC",     "COINONE",
                                                   "CHBTC",          "BINANCE",    "EXMO",
                                                   "CRYPTOPIA",      "LIQUI",      "JUBI",
                                                   "BTC38",          "KORBIT",     "MTGOX",
                                                   "LAKEBTC",        "BLEUTRADE",  "YOBIT",
                                                   "BITFLYER",       "BTER",       "ACX",
                                                   "VIRWOX",         "OKEX",       "THEROCKTRADING",
                                                   "MERCADOBITCOIN", "QUOINE",     "BITMARKET",
                                                   "BITSO",          "VAULTORO",   "CCEX",
                                                   "GATECOIN",       "QUADRIGACX", "COINMATE",
                                                   "BXINTH",         "COINFLOOR",  "INDEPENDENTRESERVE",
                                                   "COINNEST",       "WEXNZ",      "DERIBIT",
                                                   "BTCX",           "DSX",        "YUNBI",
                                                   "BITKONAN",       "BTCC",       "BITBAY",
                                                   "BTCTURK",        "XBTCE"};

#endif  // EXCHANGE_ENUMS_H
